services:
  admin:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_AUTH_GOOGLE_ID: ${NEXT_PUBLIC_AUTH_GOOGLE_ID}
        NEXT_PUBLIC_AUTH_FACEBOOK_ID: ${NEXT_PUBLIC_AUTH_FACEBOOK_ID}
        NEXT_PUBLIC_AUTH_APPLE_ID: ${NEXT_PUBLIC_AUTH_APPLE_ID}
    env_file:
      - .env
    ports:
      - "3001:3001"
